# CLI Tools (migrated from devbox)
brew "atuin"
brew "bat"
brew "btop"
brew "cheat"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "glab"
brew "htop"
brew "jq"
brew "just"
brew "lazygit"
brew "libsodium"
brew "neofetch"
brew "pandoc"
brew "ripgrep"
# brew "starship"  # using powerlevel10k instead
brew "tlrc"
brew "tmux"
brew "tree-sitter"
brew "wget"
brew "yq"
brew "zoxide"

# Programming Related
brew "bitwarden-cli"
brew "gh"
brew "helix"
brew "mise"
brew "ollama"
brew "sesh"
brew "yadm"

cask "claude-code"

brew "aws-vault"
brew "awscli"
# brew "curl"
# brew "neovim"
# brew "zsh-autosuggestions"
# brew "zsh-syntax-highlighting"

cask "orbstack"
brew "k9s"

# Terminals
cask "alacritty"
cask "wezterm"
cask "warp"

# Fonts
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-monaspice-nerd-font"
cask "font-symbols-only-nerd-font"

# General
brew "cmake"
brew "gnupg" if OS.mac?
brew "glibc" if OS.linux?
brew "coreutils" if OS.linux?
brew "glow"
brew "oath-toolkit"
brew "pkg-config"
brew "xz"

# Code / Text Editors
# brew "neovim"
# brew "vim"
cask "cursor"
cask "visual-studio-code"

# Productivity Apps
cask "obsidian"
cask "discord"
cask "firefox"
# cask "logi-options-plus"
cask "nordvpn"
cask "rectangle"

# Playing Around
# cask "vlc"
cask "pear-devs/pear/pear-desktop"
