- name: 'Setup repositories'
  hosts: localhost
  vars:
    documents: '{{ lookup("env", "HOME") }}/Documents'
    personal: '{{ lookup("env", "HOME") }}/dev'
    open_source: '{{ lookup("env", "HOME") }}/dev/repos/open-source'

  tasks:
  # - name: 'Clone documents repos'
  #   git:
  #     repo: 'git@github.com:andperks/{{ item }}.git'
  #     dest: '{{ documents }}/{{ item }}'
  #   loop:
  #     - notes
  #     - pass

  - name: 'Clone personal repos'
    git:
      repo: 'git@github.com:andperks/{{ item }}.git'
      dest: '{{ personal }}/{{ item }}'
    loop:
      - otter-eats-sanity
      - mirror-mirror-UI

  - name: 'Install personal repos'
    shell:
      chdir: '{{ personal }}/{{ item }}'
      cmd: 'just install'
    loop:
      - cli
      - pass-yank

  - name: 'Clone open source repos'
    git:
      repo: 'git@github.com:{{ item.user }}/{{ item.name }}.git'
      dest: '{{ open_source }}/{{ item.name }}'
    loop:
      - { user: 'kdheepak', name: 'panvimdoc' }
